#!/usr/bin/python
# coding=utf-8
import requests
import unittest
import json
from common.public import *
import random

class ICEM_Interface(unittest.TestCase):

    @classmethod
    def setUpClass(self):
        self.headers = headers
        self.host = host
        self.path = "/api/icem-system/system/role/save"
        self.random = random.randint(1000,99999)
        print("----------开始测试----------")


    #创建角色接口
    def test_createRole(self):
        self.url = self.host + self.path
        self.roleName = "自动化角色" + str(self.random)
        data = {
	"roleName": self.roleName,
	"description": "自动化角色描述",
	"resources": [{
		"id": 2,
		"isDataResource": "NO",
		"parentId": 1,
		"perms": "cdp:dashboard",
		"resourceName": "数据仪表盘",
		"resourceType": "MENU"
	}, {
		"id": 4,
		"isDataResource": "NO",
		"parentId": 3,
		"perms": "cdp:customer:infoview",
		"resourceName": "客户信息概览",
		"resourceType": "MENU"
	}, {
		"id": 5,
		"isDataResource": "NO",
		"parentId": 3,
		"perms": "cdp:customer:list",
		"resourceName": "客户列表",
		"resourceType": "MENU"
	}, {
		"id": 6,
		"isDataResource": "NO",
		"parentId": 3,
		"perms": "cdp:customer:blacklist",
		"resourceName": "黑名单列表",
		"resourceType": "MENU"
	}, {
		"id": 8,
		"isDataResource": "NO",
		"parentId": 7,
		"perms": "cdp:crowd:customlist",
		"resourceName": "自定义人群",
		"resourceType": "MENU"
	}, {
		"id": 9,
		"isDataResource": "NO",
		"parentId": 7,
		"perms": "cdp:crowd:uploadlist",
		"resourceName": "上传人群",
		"resourceType": "MENU"
	}, {
		"id": 11,
		"isDataResource": "NO",
		"parentId": 10,
		"perms": "cdp:label:list",
		"resourceName": "自定义标签",
		"resourceType": "MENU"
	}, {
		"id": 13,
		"isDataResource": "NO",
		"parentId": 12,
		"perms": "cdp:systemconfig:datasource",
		"resourceName": "数据源配置",
		"resourceType": "MENU"
	}, {
		"id": 16,
		"isDataResource": "NO",
		"parentId": 15,
		"perms": "cem:marketing:smartlist",
		"resourceName": "营销管理",
		"resourceType": "MENU"
	}, {
		"id": 18,
		"isDataResource": "NO",
		"parentId": 17,
		"perms": "cem:wechat:account",
		"resourceName": "公众号管理",
		"resourceType": "MENU"
	}, {
		"id": 19,
		"isDataResource": "NO",
		"parentId": 17,
		"perms": "cem:wechat:material",
		"resourceName": "素材管理",
		"resourceType": "MENU"
	}, {
		"id": 20,
		"isDataResource": "NO",
		"parentId": 17,
		"perms": "cem:wechat:custommenu",
		"resourceName": "自定义菜单",
		"resourceType": "MENU"
	}, {
		"id": 21,
		"isDataResource": "NO",
		"parentId": 17,
		"perms": "cem:wechat:autoreply",
		"resourceName": "自动回复",
		"resourceType": "MENU"
	}, {
		"id": 22,
		"isDataResource": "NO",
		"parentId": 17,
		"perms": "cem:wechat:coupons",
		"resourceName": "微信优惠券",
		"resourceType": "MENU"
	}, {
		"id": 23,
		"isDataResource": "NO",
		"parentId": 17,
		"perms": "cem:wechat:massmessage",
		"resourceName": "群发消息",
		"resourceType": "MENU"
	}, {
		"id": 25,
		"isDataResource": "NO",
		"parentId": 24,
		"perms": "cem:sms:accountview",
		"resourceName": "帐号概况",
		"resourceType": "MENU"
	}, {
		"id": 26,
		"isDataResource": "NO",
		"parentId": 24,
		"perms": "cem:sms:template",
		"resourceName": "模版管理",
		"resourceType": "MENU"
	}, {
		"id": 27,
		"isDataResource": "NO",
		"parentId": 24,
		"perms": "cem:sms:parameter",
		"resourceName": "参数管理",
		"resourceType": "MENU"
	}, {
		"id": 30,
		"isDataResource": "NO",
		"parentId": 29,
		"perms": "setting:account:role",
		"resourceName": "角色管理",
		"resourceType": "MENU"
	}, {
		"id": 31,
		"isDataResource": "NO",
		"parentId": 29,
		"perms": "setting:account:childaccount",
		"resourceName": "子帐号管理",
		"resourceType": "MENU"
	}, {
		"id": 33,
		"isDataResource": "NO",
		"parentId": 32,
		"perms": "setting:log:system",
		"resourceName": "系统操作日志",
		"resourceType": "MENU"
	}, {
		"id": 34,
		"isDataResource": "NO",
		"parentId": 32,
		"perms": "setting:log:operating",
		"resourceName": "运营操作日志",
		"resourceType": "MENU"
	}, {
		"id": 36,
		"isDataResource": "NO",
		"parentId": 35,
		"perms": "setting:personalacc:resetpwd",
		"resourceName": "修改密码",
		"resourceType": "MENU"
	}, {
		"id": 37,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:lastseven",
		"resourceName": "查看最近7天",
		"resourceType": "BUTTON"
	}, {
		"id": 38,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:lastfifteen",
		"resourceName": "查看最近15天",
		"resourceType": "BUTTON"
	}, {
		"id": 39,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:lastthirty",
		"resourceName": "查看最近30天",
		"resourceType": "BUTTON"
	}, {
		"id": 40,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:customtime",
		"resourceName": "自定义时间",
		"resourceType": "BUTTON"
	}, {
		"id": 41,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:export",
		"resourceName": "导出报表",
		"resourceType": "BUTTON"
	}, {
		"id": 42,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:savecrowed",
		"resourceName": "保存人群",
		"resourceType": "BUTTON"
	}, {
		"id": 43,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:overview",
		"resourceName": "数据资产概览数据",
		"resourceType": "BUTTON"
	}, {
		"id": 44,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:lifecycle",
		"resourceName": "客户生命周期数据",
		"resourceType": "BUTTON"
	}, {
		"id": 45,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:customervalue",
		"resourceName": "查看客户价值数据",
		"resourceType": "BUTTON"
	}, {
		"id": 46,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:customerrelationship",
		"resourceName": "查看客户关系数据",
		"resourceType": "BUTTON"
	}, {
		"id": 47,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:purchasefrequency",
		"resourceName": "查看客户购买频率",
		"resourceType": "BUTTON"
	}, {
		"id": 48,
		"isDataResource": "NO",
		"perms": "cdp:dashboard:characteristics",
		"resourceName": "查看客户客单价特征",
		"resourceType": "BUTTON"
	}, {
		"id": 49,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:infosearch",
		"resourceName": "客户基础信息筛选",
		"resourceType": "BUTTON"
	}, {
		"id": 50,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:consumptionsearch",
		"resourceName": "消费信息筛选",
		"resourceType": "BUTTON"
	}, {
		"id": 51,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:wechatsearch",
		"resourceName": "微信公众号关注筛选",
		"resourceType": "BUTTON"
	}, {
		"id": 52,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:addlabel",
		"resourceName": "批量添加标签",
		"resourceType": "BUTTON"
	}, {
		"id": 53,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:addblack",
		"resourceName": "加入黑名单",
		"resourceType": "BUTTON"
	}, {
		"id": 54,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:portrait",
		"resourceName": "查看个人画像",
		"resourceType": "BUTTON"
	}, {
		"id": 55,
		"isDataResource": "NO",
		"perms": "cdp:customer:list:insight",
		"resourceName": "查看个人商业洞察",
		"resourceType": "BUTTON"
	}, {
		"id": 56,
		"isDataResource": "NO",
		"perms": "cdp:customer:blacklist:search",
		"resourceName": "黑名单搜索",
		"resourceType": "BUTTON"
	}, {
		"id": 57,
		"isDataResource": "NO",
		"perms": "cdp:customer:blacklist:removeblack",
		"resourceName": "移出黑名单",
		"resourceType": "BUTTON"
	}, {
		"id": 58,
		"isDataResource": "NO",
		"perms": "cdp:customer:blacklist:portrait",
		"resourceName": "查看个人画像",
		"resourceType": "BUTTON"
	}, {
		"id": 59,
		"isDataResource": "NO",
		"perms": "cdp:customer:blacklist:insight",
		"resourceName": "查看个人商业洞察",
		"resourceType": "BUTTON"
	}, {
		"id": 60,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:search",
		"resourceName": "人群检索",
		"resourceType": "BUTTON"
	}, {
		"id": 61,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:create",
		"resourceName": "新建人群",
		"resourceType": "BUTTON"
	}, {
		"id": 62,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:update",
		"resourceName": "更新人群",
		"resourceType": "BUTTON"
	}, {
		"id": 63,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:performance",
		"resourceName": "查看人群绩效",
		"resourceType": "BUTTON"
	}, {
		"id": 64,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:portrait",
		"resourceName": "查看人群画像",
		"resourceType": "BUTTON"
	}, {
		"id": 65,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:insight",
		"resourceName": "查看人群商业洞察",
		"resourceType": "BUTTON"
	}, {
		"id": 66,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:copy",
		"resourceName": "人群复制",
		"resourceType": "BUTTON"
	}, {
		"id": 67,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:packaging",
		"resourceName": "人群打包",
		"resourceType": "BUTTON"
	}, {
		"id": 68,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:delete",
		"resourceName": "删除人群",
		"resourceType": "BUTTON"
	}, {
		"id": 69,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:save",
		"resourceName": "保存人群",
		"resourceType": "BUTTON"
	}, {
		"id": 70,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:export",
		"resourceName": "导出人群",
		"resourceType": "BUTTON"
	}, {
		"id": 71,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:portrait",
		"resourceName": "查看人群画像",
		"resourceType": "BUTTON"
	}, {
		"id": 72,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:tagselect",
		"resourceName": "标签选择",
		"resourceType": "BUTTON"
	}, {
		"id": 73,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:detail",
		"resourceName": "查看各标签人群分布详情",
		"resourceType": "BUTTON"
	}, {
		"id": 74,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:breakup",
		"resourceName": "拆分人群包",
		"resourceType": "BUTTON"
	}, {
		"id": 75,
		"isDataResource": "NO",
		"perms": "cdp:crowd:customlist:export",
		"resourceName": "导出人群包",
		"resourceType": "BUTTON"
	}, {
		"id": 76,
		"isDataResource": "NO",
		"perms": "cdp:crowd:uploadlist:search",
		"resourceName": "人群检索",
		"resourceType": "BUTTON"
	}, {
		"id": 77,
		"isDataResource": "NO",
		"perms": "cdp:crowd:uploadlist:upload",
		"resourceName": "上传人群",
		"resourceType": "BUTTON"
	}, {
		"id": 78,
		"isDataResource": "NO",
		"perms": "cdp:crowd:uploadlist:detail",
		"resourceName": "查看人群详情",
		"resourceType": "BUTTON"
	}, {
		"id": 79,
		"isDataResource": "NO",
		"perms": "cdp:crowd:uploadlist:packaging",
		"resourceName": "人群打包",
		"resourceType": "BUTTON"
	}, {
		"id": 80,
		"isDataResource": "NO",
		"perms": "cdp:crowd:uploadlist:delete",
		"resourceName": "人群打包",
		"resourceType": "BUTTON"
	}, {
		"id": 81,
		"isDataResource": "NO",
		"perms": "cdp:label:list:add",
		"resourceName": "添加标签",
		"resourceType": "BUTTON"
	}, {
		"id": 82,
		"isDataResource": "NO",
		"perms": "cdp:label:list:delete",
		"resourceName": "删除标签",
		"resourceType": "BUTTON"
	}, {
		"id": 83,
		"isDataResource": "NO",
		"perms": "cdp:systemconfig:datasource:edit",
		"resourceName": "修改数据源接口的secret",
		"resourceType": "BUTTON"
	}, {
		"id": 84,
		"isDataResource": "NO",
		"perms": "cdp:systemconfig:datasource:delete",
		"resourceName": "删除数据源",
		"resourceType": "BUTTON"
	}, {
		"id": 85,
		"isDataResource": "NO",
		"perms": "cdp:systemconfig:datasource:add",
		"resourceName": "新增数据源",
		"resourceType": "BUTTON"
	}, {
		"id": 86,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:create",
		"resourceName": "创建营销活动",
		"resourceType": "BUTTON"
	}, {
		"id": 87,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:detail",
		"resourceName": "查看营销活动详情”",
		"resourceType": "BUTTON"
	}, {
		"id": 88,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:edit",
		"resourceName": "编辑营销活动",
		"resourceType": "BUTTON"
	}, {
		"id": 89,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:start",
		"resourceName": "开始营销活动”",
		"resourceType": "BUTTON"
	}, {
		"id": 90,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:delete",
		"resourceName": "删除营销活动",
		"resourceType": "BUTTON"
	}, {
		"id": 91,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:analysis",
		"resourceName": "活动效果分析",
		"resourceType": "BUTTON"
	}, {
		"id": 92,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:save",
		"resourceName": "保存模板",
		"resourceType": "BUTTON"
	}, {
		"id": 93,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:test",
		"resourceName": "测试执行",
		"resourceType": "BUTTON"
	}, {
		"id": 94,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:run",
		"resourceName": "正式执行",
		"resourceType": "BUTTON"
	}, {
		"id": 95,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:customerscreening",
		"resourceName": "圈人节点-客群选人",
		"resourceType": "BUTTON"
	}, {
		"id": 96,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:orderscreening",
		"resourceName": "圈人节点-订单筛选",
		"resourceType": "BUTTON"
	}, {
		"id": 97,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:wechatscreening",
		"resourceName": "圈人节点-微信公众号选人",
		"resourceType": "BUTTON"
	}, {
		"id": 98,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:activityscreening",
		"resourceName": "圈人节点-营销活动筛选",
		"resourceType": "BUTTON"
	}, {
		"id": 99,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:merge",
		"resourceName": "计算节点-合并",
		"resourceType": "BUTTON"
	}, {
		"id": 100,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:intersection",
		"resourceName": "计算节点-交集",
		"resourceType": "BUTTON"
	}, {
		"id": 101,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:ruleout",
		"resourceName": "计算节点-排除",
		"resourceType": "BUTTON"
	}, {
		"id": 102,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:generate",
		"resourceName": "计算节点-生成目标组",
		"resourceType": "BUTTON"
	}, {
		"id": 103,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:sms",
		"resourceName": "下行渠道-短信",
		"resourceType": "BUTTON"
	}, {
		"id": 104,
		"isDataResource": "NO",
		"perms": "cem:marketing:smartlist:wechatgraphic",
		"resourceName": "下行渠道-微信图文",
		"resourceType": "BUTTON"
	}, {
		"id": 105,
		"isDataResource": "NO",
		"perms": "cem:wechat:material:graphic",
		"resourceName": "微信图文",
		"resourceType": "BUTTON"
	}, {
		"id": 106,
		"isDataResource": "NO",
		"perms": "cem:wechat:material:img",
		"resourceName": "图片",
		"resourceType": "BUTTON"
	}, {
		"id": 107,
		"isDataResource": "NO",
		"perms": "cem:wechat:material:audio",
		"resourceName": "音频",
		"resourceType": "BUTTON"
	}, {
		"id": 108,
		"isDataResource": "NO",
		"perms": "cem:wechat:material:video",
		"resourceName": "视频",
		"resourceType": "BUTTON"
	}, {
		"id": 109,
		"isDataResource": "NO",
		"perms": "cem:wechat:custommenu:setting",
		"resourceName": "自定义菜单设置",
		"resourceType": "BUTTON"
	}, {
		"id": 110,
		"isDataResource": "NO",
		"perms": "cem:wechat:autoreply:create",
		"resourceName": "新建自动回复",
		"resourceType": "BUTTON"
	}, {
		"id": 111,
		"isDataResource": "NO",
		"perms": "cem:wechat:autoreply:edit",
		"resourceName": "编辑自动回复",
		"resourceType": "BUTTON"
	}, {
		"id": 112,
		"isDataResource": "NO",
		"perms": "cem:wechat:autoreply:delete",
		"resourceName": "删除自动回复",
		"resourceType": "BUTTON"
	}, {
		"id": 113,
		"isDataResource": "NO",
		"perms": "cem:wechat:coupons:search",
		"resourceName": "搜索优惠券",
		"resourceType": "BUTTON"
	}, {
		"id": 114,
		"isDataResource": "NO",
		"perms": "cem:wechat:coupons:create",
		"resourceName": "创建优惠券",
		"resourceType": "BUTTON"
	}, {
		"id": 115,
		"isDataResource": "NO",
		"perms": "cem:wechat:coupons:edit",
		"resourceName": "编辑优惠券",
		"resourceType": "BUTTON"
	}, {
		"id": 116,
		"isDataResource": "NO",
		"perms": "cem:wechat:coupons:detail",
		"resourceName": "查看优惠券详情",
		"resourceType": "BUTTON"
	}, {
		"id": 117,
		"isDataResource": "NO",
		"perms": "cem:wechat:coupons:statistical",
		"resourceName": "查看优惠券相关统计",
		"resourceType": "BUTTON"
	}, {
		"id": 118,
		"isDataResource": "NO",
		"perms": "cem:wechat:coupons:delete",
		"resourceName": "删除优惠券",
		"resourceType": "BUTTON"
	}, {
		"id": 119,
		"isDataResource": "NO",
		"perms": "cem:wechat:autoreply:create",
		"resourceName": "新建自动回复",
		"resourceType": "BUTTON"
	}, {
		"id": 120,
		"isDataResource": "NO",
		"perms": "cem:wechat:autoreply:edit",
		"resourceName": "编辑自动回复",
		"resourceType": "BUTTON"
	}, {
		"id": 121,
		"isDataResource": "NO",
		"perms": "cem:wechat:autoreply:delete",
		"resourceName": "删除自动回复",
		"resourceType": "BUTTON"
	}, {
		"id": 122,
		"isDataResource": "NO",
		"perms": "cem:sms:accountview:record",
		"resourceName": "搜索短信发送记录",
		"resourceType": "BUTTON"
	}, {
		"id": 123,
		"isDataResource": "NO",
		"perms": "cem:sms:accountview:detail",
		"resourceName": "查看短信发送记录明细",
		"resourceType": "BUTTON"
	}, {
		"id": 124,
		"isDataResource": "NO",
		"perms": "cem:sms:template:search",
		"resourceName": "搜索模板",
		"resourceType": "BUTTON"
	}, {
		"id": 125,
		"isDataResource": "NO",
		"perms": "cem:sms:template:create",
		"resourceName": "创建模板",
		"resourceType": "BUTTON"
	}, {
		"id": 126,
		"isDataResource": "NO",
		"perms": "cem:sms:template:edit",
		"resourceName": "修改模板",
		"resourceType": "BUTTON"
	}, {
		"id": 127,
		"isDataResource": "NO",
		"perms": "cem:sms:template:delete",
		"resourceName": "删除模板",
		"resourceType": "BUTTON"
	}, {
		"id": 128,
		"isDataResource": "NO",
		"perms": "setting:account:role:add",
		"resourceName": "添加角色",
		"resourceType": "BUTTON"
	}, {
		"id": 129,
		"isDataResource": "NO",
		"perms": "setting:account:role:delete",
		"resourceName": "删除角色",
		"resourceType": "BUTTON"
	}, {
		"id": 130,
		"isDataResource": "NO",
		"perms": "setting:account:role:edit",
		"resourceName": "编辑角色",
		"resourceType": "BUTTON"
	}, {
		"id": 131,
		"isDataResource": "NO",
		"perms": "setting:account:childaccount:search",
		"resourceName": "搜索子账号",
		"resourceType": "BUTTON"
	}, {
		"id": 132,
		"isDataResource": "NO",
		"perms": "setting:account:childaccount:add",
		"resourceName": "添加子账号",
		"resourceType": "BUTTON"
	}, {
		"id": 133,
		"isDataResource": "NO",
		"perms": "setting:account:childaccount:delete",
		"resourceName": "删除子账号",
		"resourceType": "BUTTON"
	}, {
		"id": 134,
		"isDataResource": "NO",
		"perms": "setting:account:childaccount:edit",
		"resourceName": "编辑子帐号",
		"resourceType": "BUTTON"
	}, {
		"id": 135,
		"isDataResource": "NO",
		"perms": "setting:account:childaccount:resetpwd",
		"resourceName": "密码重置",
		"resourceType": "BUTTON"
	}, {
		"id": 136,
		"isDataResource": "NO",
		"perms": "setting:log:system:search",
		"resourceName": "搜索日志",
		"resourceType": "BUTTON"
	}, {
		"id": 137,
		"isDataResource": "NO",
		"perms": "setting:log:operating:search",
		"resourceName": "搜索日志",
		"resourceType": "BUTTON"
	}, {
		"id": 138,
		"isDataResource": "NO",
		"perms": "setting:personalacc:resetpwd:edit",
		"resourceName": "修改密码",
		"resourceType": "BUTTON"
	}]
}

        response = requests.post(url=self.url,data= json.dumps(data), headers=self.headers)
        print (response.text)
        self.deleteId = str(response.json()['id'])
        assert response.json()['error'] == 0


    def tearDown(self):
        # self.deletePath = "/api/icem-system/system/role/delete"
        # self.deleteUrl = self.host + self.deletePath
        # deleteData = {"ids":[self.deleteId]}
        # res = requests.post(url=self.deleteUrl, data=json.dumps(deleteData), headers=self.headers)
        # print(res.text)
        pass

if __name__ == "__main__":
    sms = ICEM_Interface()